
query SearchDossierByName($nom: String!,$prenom: String!){
  dossiers  (where: {client:{nom:{contains:$nom} and : {prenom:{contains:$prenom}}}}){
    dossierId
    dateArrivee
    dureeSejourJours
    numeroVol
    lieu
    clientId
    typeVoyageId
    actif
    client{
      nom
      prenom
      numeroTelephone
      email
      nationalite
      actif
    }

    typeVoyage{
      libelle
    }

    hotel {
      nom
      nombreEtoiles
      pays
      ville
      adresse
      description
      prix
     
    }
  }
}